(CI) Enable build with latest gegelati version of matching branch (develop & master)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,7 @@
 name: CI
 on: [push, pull_request, workflow_dispatch]
 jobs:
-  Generic:
+  Generic: # run with gegelati version of the submodule repo
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -19,6 +19,53 @@ jobs:
       - name: Compile appli
         run: |
           cd ${{ matrix.app }}/bin
+          if [ "${{ matrix.os }}" = "windows-latest" ]; then cmake .. -DTESTING=1 ; fi
+          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then cmake .. -DTESTING=1 -DCMAKE_BUILD_TYPE=Release ; fi
+          if [ "${{ matrix.os }}" = "windows-latest" ]; then cmake --build . --target ${{ matrix.app }} --config Release ; fi
+          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then cmake --build . --target ${{ matrix.app }} ; fi
+        shell: bash
+      - name: Run appli
+        run: ./${{ matrix.app }}/bin/Release/${{ matrix.app }}
+        shell: bash
+  Latest: # run app with latest gegelati version
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+        app: [pendulum]
+      fail-fast: false # Continue running all jobs even if one fails
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          submodules: 'true' # Checkout all submodules
+      - name: Install Doxygen
+        if: matrix.os == 'ubuntu-latest'
+        run: sudo apt install doxygen
+      - name: Install gegelati Windows
+        if: matrix.os == 'windows-latest'
+        run: |
+          if [[ "${{ github.ref }}" == *"master" ]] || [[ "${{ github.base_ref }}" == *"master" ]] || [[ "${{ github.ref }}" == *"tags/v"* ]]; then curl -L -J $(curl -s https://api.github.com/repos/gegelati/gegelati/releases/latest | grep "browser_download_url.*gegelatilib-msvc.*zip" | cut -d':' -f 2,3 | tr -d \") -o gegelatilib-latest.zip; else curl https://gegelati.github.io/neutral-builds/gegelatilib-msvc-latest-develop.zip -o gegelatilib-latest.zip;  fi
+          7z x gegelatilib-latest.zip
+          echo "LATEST_FOLDER=$(find -maxdepth 1 -regextype posix-egrep -regex "./gegelatilib-[0-9]+\.[0-9]+\.[0-9]+\$" | cut -d'/' -f 2)" >> $GITHUB_ENV
+        shell: bash
+      - name: Install gegelati Ubuntu
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          git clone --branch $([ ${GITHUB_REF##*/} == "master" ] && echo "master" || echo "develop") $() https://github.com/gegelati/gegelati.git
+          cd gegelati/bin
+          cmake .. -DCMAKE_BUILD_TYPE=Release
+          sudo make install
+      - name: Switch app to matching branch
+        run: |
+          git submodule set-branch --branch $([ ${GITHUB_REF##*/} == "master" ] && echo "main" || echo "develop") ${{ matrix.app }} 
+          git submodule update --remote --checkout ${{ matrix.app }}
+        shell: bash
+      - name: Compile appli
+        run: |
+          cd ${{ matrix.app }}
+          if [ "${{ matrix.os }}" = "windows-latest" ]; then cp -r ../${LATEST_FOLDER} ./lib/ ; fi
+          cd bin
           if [ "${{ matrix.os }}" = "windows-latest" ]; then cmake .. -DTESTING=1 ; fi
           if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then cmake .. -DTESTING=1 -DCMAKE_BUILD_TYPE=Release ; fi
           if [ "${{ matrix.os }}" = "windows-latest" ]; then cmake --build . --target ${{ matrix.app }} --config Release ; fi
